name: groceries_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  country_code_picker: ^2.0.2
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/SVN-Gilroy-Regular.otf
        - asset: assets/fonts/SVN-Gilroy-Medium.otf
          weight: 500 
        - asset: assets/fonts/SVN-Gilroy-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SVN-Gilroy-Bold.otf
          weight: 700
        
    
  
